improve legacy file version parsing
asdf-vm/asdf-nodejs pull request #204
Opened 2021-02-12 02:40 UTC by AaronLasseigne

This adds support for "node" and partial version numbers (e.g. "14", "14.15"). It doesn't add LTS but there's another PR for that (#194). If both are acceptable I'm sure they can be reconciled.

2021-02-16 22:25 UTC, Stratus3D commented
Thanks for the PR. I am not sure we should merge either of these pull requests. asdf versions should be exact. Files that don't specify exact versions, or that specify ranges shouldn't really be used. See https://github.com/asdf-vm/asdf-nodejs/issues/60#issuecomment-567547590 where I touched on this briefly:

> Here is a PR that attempts to add support for package.json - #120. The problem with this PR is that the engine value isn't a plain version that can be used by asdf-nodejs. We would have to address all the issues nvm would have to address on their PR.

I know there has been some recent discussion about this on #194 and #193 and I've not had a chance to catch up on everything.

2021-02-16 23:02 UTC, AaronLasseigne commented
All of these are really because [`.nvmrc` files support this stuff](https://github.com/nvm-sh/nvm#nvmrc). I understand that you might have reasons not to support it. If that's the case then I would suggest a revision to the readme which states that legacy file support is limited and only works for exact versions.

2021-02-17 14:47 UTC, augustobmoura commented
Supporting only the major version today can be achieved in the same vein of #194, where we symlink the major version number to a version already installed locally, `$ASDF_DIR/installs/nodejs` would have something like:
 ```
lrwxrwxrwx 1 aumoura aumoura    7 Feb 17 11:44 14 -> 14.15.4
drwxrwxr-x 2 aumoura aumoura 4.0K Feb 17 11:44 14.15.4
```

> Thanks for the PR. I am not sure we should merge either of these pull requests. asdf versions should be exact. Files that don't specify exact versions, or that specify ranges shouldn't really be used. See [#60 (comment)](https://github.com/asdf-vm/asdf-nodejs/issues/60#issuecomment-567547590) where I touched on this briefly:
> 
> > Here is a PR that attempts to add support for package.json - #120. The problem with this PR is that the engine value isn't a plain version that can be used by asdf-nodejs. We would have to address all the issues nvm would have to address on their PR.

package.json engines field is a very different beast, it's actually a dynamic [semver expression](https://www.npmjs.com/package/semver) with very complex combinations, supporting aliases to partial versions (`14` or `14.3` for example) should be relatively easy to implement.

About your comment https://github.com/asdf-vm/asdf-nodejs/issues/60#issuecomment-567547590
> package.json specifies a version or range of versions that the package is compatible with, whereas .tool-versions and .node-version specify a single version that must be used. We'd have to implement our own logic for choosing the highest or lowest version for the package, or maybe prefer a version the user already has installed. That gets very complicated. I think we should just stick with .tool-versions and .node-version.

Currently we are already implementing a preference algorithm for lts aliases, the implementation is not complicated but it is debatable and not without edge cases, the algorithm is like:
1. if the alias is already installed, ignore the install
2. if is not installed find the latest version for that branch/channel and install it
3. symlink the lts to the version installed in 2

It's hardly expected that all new versions in a lts branch do not introduce breaking changes so it's okay to fetch the latest one, nvm does implement a flag to install the earliest, we can postpone this flag until the need arise but it should also be easy to implement

There one hole in the implementation that I found dogfooding it, after symlinking the lts alias will be pinned to a specific version even tough a new one is released, needing a reinstall to relink it to the newest version, manual linking to different versions also work

We can discuss if this is the right approach

2021-02-17 15:45 UTC, augustobmoura requested changes

2021-02-17 15:45 UTC, augustobmoura commented on bin/parse-legacy-file
> +fi
I think we could move the translation logic to the install script, specifically into the [resolve_version_query](https://github.com/asdf-vm/asdf-nodejs/blob/5a46614ec24177146541543d3ec6327e136ae80f/bin/install#L94) function, and keep the parse-legacy-file simple

We would also remove the dependency of `asdf list` in this file, the `list` command is not meant to be used in quick scripts and perform a lot of operations that are not exactly light

2021-02-17 15:45 UTC, augustobmoura commented on bin/parse-legacy-file
> +if [[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
I advise against using bash specific features and to keep the posix compatibility where possible, we had problems in the past with bashims and we like to keep the idea of eventually removing the bash dependency.

Try using `grep` or [expr](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/expr.html) and prefer the `*` regex modifier to the extended regex `+`. A neat posix version of this line would be:
```suggestion
if expr "$version" : '^[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$'; then
```

2021-12-29 21:15 UTC, closed without merging