if a version is not installable via node-build, make sure it is not in list-all
asdf-vm/asdf-nodejs pull request #292
Opened 2022-03-11 14:39 UTC by burnettk

this intends to fix the issue that caused the build failure in https://github.com/asdf-vm/asdf-nodejs/runs/5504696864. it also happened when several of my colleagues tried to run our [local dev setup script](https://github.com/no-term-limits/no-term-limits). doh. :) the only change between the previous output of `asdf list-all nodejs` and the output produced by the new version is that the following versions no longer appear:

````
17.7.0
17.7.1
````

2022-03-11 15:29 UTC, augustobmoura commented
Hi @burnettk, thanks for the contribution! And sorry for the broken scripts, we should definitely fix that

I was thinking that instead of checking if the version is on `nodebuild` on install, we should replace our `list-all` script with a call to the local `nodebuild` installation, similar to how [`asfd-ruby`](https://github.com/asdf-vm/asdf-ruby/blob/master/bin/list-all) and [`asdf-python`](https://github.com/danhper/asdf-python/blob/master/bin/list-all) do it, wdyt?

If that is the case, we gonna need to make some changes to the `nodebuild` listing. We are trying to avoid aliasing on asdf plugins for some use cases (long story short, it should be fine to use `asdf install nodejs lts` but putting `lts` in a `.tool-versions` file shouldn't work). Because we had the `lts`es before this discussion we still gonna need to support them for now, but it would be better to get rid of the other aliases that `nodebuild` provides (mostly `-dev` and `-nightly` branches).

It should be pretty simple though, just a simple grep and printing the `lts` aliases manually should do the work

2022-03-11 16:58 UTC, augustobmoura commented
Yep, nodebuild doesn't have named lts aliases, but we could just manually print the aliases for now, they don't change that often. Something like:

``` bash
printf "%s\n" lts-{argon,boron,carbon,dubnium,erbium,fermium,gallium} lts
```

2022-03-11 17:50 UTC, burnettk commented
sure, ok, i went ahead and did that. `diff <(sort asdf-list-all) <(sort list-all-new)` is still showing what i would expect (just the two versions are different). now it's just using print_index_tab (and the corresponding http endpoint) for bin/install.

2022-03-11 18:22 UTC, augustobmoura requested changes

2022-03-11 18:22 UTC, augustobmoura commented on bin/list-all
> +all_definitions_from_node_build="$("${asdf_nodejs_bin_dir}/../.node-build/bin/node-build" --definitions)"
We have and wrapper script around node-build to make it easier to run it with the necessary variables, check the install script for [an example](https://github.com/asdf-vm/asdf-nodejs/blob/364c0783408e25130c254abfaaec4747404c8f5e/bin/install#L37)

```suggestion
all_definitions_from_node_build="$("$ASDF_NODEJS_PLUGIN_DIR/lib/commands/command-nodebuild.bash"--definitions)"
```

2022-03-11 18:22 UTC, augustobmoura commented on bin/list-all
> +  print_only_fully_numeric_items "$all_definitions_from_node_build"
I think it's better to show the lts aliases after the numbered versions, to make they more apparent
```suggestion
  print_only_fully_numeric_items "$all_definitions_from_node_build"
  printf "%s\n" lts-{argon,boron,carbon,dubnium,erbium,fermium,gallium} lts
```

2022-03-14 13:06 UTC, augustobmoura commented
Also, before running nodebuild we need to ensure it's installed, there's a [script for that](https://github.com/asdf-vm/asdf-nodejs/blob/364c0783408e25130c254abfaaec4747404c8f5e/bin/install#L25) as well. I think this is why the pipeline is broken

2022-03-14 13:07 UTC, augustobmoura requested changes

2022-03-14 13:07 UTC, augustobmoura commented on bin/list-all
> +all_definitions_from_node_build="$(nodebuild_wrapped --definitions)"
We need to ensure nodebuild is installed before calling it
```suggestion
"$ASDF_NODEJS_PLUGIN_DIR/lib/commands/command-update-nodebuild.bash" &> /dev/null

all_definitions_from_node_build="$(nodebuild_wrapped --definitions)"
```

2022-03-14 18:03 UTC, augustobmoura approved these changes

2022-03-14 18:03 UTC, merged