Add "--location" to curl_opts
asdf-vm/asdf-nodejs pull request #340
Opened 2023-02-21 15:30 UTC by ygxxii

If set `NODEJS_ORG_MIRROR` to `npmmirror.com`, there would be a 302 response.

```bash
export NODEJS_ORG_MIRROR='https://npmmirror.com/mirrors/node/'

asdf list all nodejs
```

Add `--location` option to follow redirects.

2023-02-21 19:51 UTC, Kurt-von-Laven approved these changes

2023-02-21 20:15 UTC, augustobmoura commented on lib/utils.sh
>    index=$(curl --fail --silent --dump-header "$temp_headers_file" ${curl_opts+"${curl_opts[@]}"}  "${NODEJS_ORG_MIRROR}index.tab")
Right now the header is only being added if we have some cache already installed. We want always to follow redirects, so we need to add it to the command itself on line 102

```suggestion
    curl_opts=(--header "If-None-Match: $(cat "$etag_file")")
  fi

  index=$(curl --fail --silent --location --dump-header "$temp_headers_file" ${curl_opts+"${curl_opts[@]}"}  "${NODEJS_ORG_MIRROR}index.tab")
```

2023-02-21 20:15 UTC, augustobmoura requested changes
Hey @ygxxii :wave:

Thanks for your contribution! I left one small comment and we be able to merge it

2023-02-28 14:00 UTC, Stratus3D approved these changes
This looks good to me now. @augustobmoura can we merge this?

2023-02-28 19:58 UTC, augustobmoura approved these changes

2023-02-28 19:59 UTC, augustobmoura commented
I think we are good to go, thanks @ygxxii!

2023-02-28 19:59 UTC, merged